/*
 * @lc app=leetcode.cn id=828 lang=typescript
 *
 * [828] 统计子串中的唯一字符
 * TODO 超时了，待二刷
 */

// @lc code=start
const countUniqueChars = (s: string) => {
  const m = new Map();
  let a = 0;
  for (let i = 0; i < s.length; i++) {
    const v = s[i];
    if (m.has(v)) {
      if (m.get(v) === 1) {
        a--;
        m.set(v, 2);
      }
    } else {
      a++;
      m.set(v, 1);
    }
  }
  return a;
};
function uniqueLetterString(s: string): number {
  const map = new Map();
  const n = s.length;
  let p = 0;
  for (let i = 0; i < n; i++) {
    let q = 0;
    for (let j = n; j > i; j--) {
      const v = s.slice(i, j);
      if (map.has(v)) {
        p += map.get(v);
      } else {
        const o = countUniqueChars(v);
        map.set(v, o);
        p += o;
      }
    }
  }
  return p;
}
// @lc code=end
console.time("a");
console.log(
  uniqueLetterString(
    "PNJBRGRPQSLSXPQBQKGGTUSHTKLLXHGXZBDMHNBZXKWZXTAANMHTOIRXHEYANOPLBVJROVZUDZNMETKKXRDMRHVMLDBHQTRIYGQFMBTZPPXGCLRJJYWHZZURDNTKWPNHLEJHFPPVQJAGSZCNUDMZWWCYUAQZGTUDMPJKLUQOSESLYGYWZKIXJQGHSOCVJQIGVXWQLOYUGFHCJSCJGHQMIGLGYAZWELSHZAPAEZQGMCMRMFRFZTTDGQUIZYDUCBVXZZUIDDCNWUAAPDUNZLBAGNIFNDBJYALQQGBRAMHBIVVERVXRTCSZSZWIGRLWZMUTEYSWZAGUDTPVLRJMOBUHOZBGHKHVOXAWCXMJNAZLQLKQQQNOCLUFGKOVBOKVKOEZEKNWHCFGCENVAABLPVTCEJVZNDTZNCRELHEDWLWIQGDBDGCTGUBZCZGTOVUFNCICJLWSMFDCRQEAGHUEVYEXQDHFFIKVECUAZRELOFJMYJJZNNJDKIMBKLRHSJUSBSTQHVLEJTJCCZQNZBVYFZXGAUDYOSCKYSMMINOANJMBAFHTNBRRZQAGLLWXLXMJANYFELMWRUFTLZUUHBSJEXOOBJKMYMLITIWJTDXSCOTZVZNVIXPDHNSXSODIEATIPIAODGCMDGYVZRJRVFCCMECCHXTIRAIQIJOWZWNRVRKOSIMQSDYRSCBONPPJTEYOEBNUOMRBIFRBQBTECLFQZTBBYROOMREHVFWTRVCODLLGJCTGUXEICJOUDMXBEVZRVRAVKIDNRICWSBNXMXVDCKZAHMQZBRLQUGTMJVOQBXARMLGJEQCORHNODVNOQFOMDPKRCOQOUDCPEOCHKHNHDGHBBYJIIYRVPKVSDYDIWOWCTGDZEHQAFDSZHJKTAYAYQCFVNAJQUQUQGFTPTRYAMLLXNSYSISFBEFNTDJWHZBWRVKRIHQXUOFBHRJKRIGJLDKRMUJQWAJGUFKSQEKMFAIJZSJIOTMCIVROAOEQPOIUD"
  )
);
console.timeEnd("a");
